### PR TITLE
Add some security headers to enchance security

### PR DESCRIPTION
**Pull request by slayerwitch**
hey, i've added some security headers in this commit with `X-Frame-Options: SAMEORIGIN` and `X-Content-Type-Options: nosniff`

if you want to learn more about these headers you can check here:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options

### CODE REVIEW

**Comment by Yonle** [comment]
This may need to be redone again in the next `nightly` branch release.

Have you tested it that it will worked well as expected?

**Comment by slayerwitch** [comment]
yes it worked well in my server, but I don't know why it doesn't work for static file like `index.html`. is there optional parameter for static file?
Screenshot from 2023-03-17 13-22-57

**Comment by slayerwitch** [comment]
oh looks like there's `setHeaders` parameter for static file in express

https://expressjs.com/en/5x/api.html#express.static

**Review by Yonle — COMMENTED** [review]
Try put the code before `app.set("views", [__dirname + "/local/views", __dirname + "/views"]);`

**Review by Yonle — APPROVED** [review]

**Comment by Yonle** [comment]
Code added to `nightly` at 47e00de

**Pull request merged**
